#!/usr/bin/env bash
# install nginx on the server.

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall (if using UFW)
sudo ufw allow 'Nginx HTTP'

# Create a simple "Hello World" index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Start the Nginx service
sudo service nginx start

